apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-webhook-nagios-nrdp.fullname" . }}
  labels:
    {{- include "alertmanager-webhook-nagios-nrdp.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
